apiVersion: v1
name: otel-demo
version: v1
dependencies: # A list of the chart requirements (optional)
  - name: opentelemetry-demo
    version: 0.36.1
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    
