mimir-distributed:  
  global:
    extraEnvFrom: 
      - secretRef:
          name: gcp-private-key

  serviceAccount:
    create: true
    name: mimir  
    annotations:
      iam.gke.io/gcp-service-account: mimir-bucket-access@elated-ranger-349805.iam.gserviceaccount.com
  enterprise:
    enabled: false       
  minio:
    enabled: false
  mimir:
    structuredConfig:
      common:
        storage:
          backend: gcs
          gcs:
            service_account: ${PRIVATE_KEY}
      blocks_storage:
        backend: gcs
        gcs:
          bucket_name: mimir-blocks
        bucket_store:
          sync_dir: "data"  

      alertmanager_storage:
        gcs:
          bucket_name: mimir-alertmanager

      ruler_storage:
        gcs:
          bucket_name: mimir-ruler
  alertmanager:
    enabled: false
  ingestor:
    replicas: 1
    zoneAwareReplication:
      enabled: false
    statefulSet:
      enabled: true
    persisentVolume:
      enabled: true  
  ruler_querier:
    replicas: 1
  querier:
    replicas: 1
  query_scheduler:
    replicas: 1
  store_gateway:
    zoneAwareReplication:
      enabled: false  
    extraArgs:
      log_level: debug

    statefulSet:
      enabled: true
    persisentVolume:
      enabled: true   

  gateway:
    enabled: false     
grafana:
  namespaceOverride: "grafana"
