mimir-distributed:  
  global:
    extraEnvFrom: 
      - secretRef:
          name: gcp-private-key
  minio:
    enabled: false
  mimir:
    structuredConfig:
      common:
        storage:
          backend: gcs
          gcs:
            service_account: |
              {
              "type": "service_account",
              "project_id": "elated-ranger-349805",
              "private_key_id": "529814b164bc8611e76b71387879388e8eb471fe",
              "private_key": ${PRIVATE_KEY},
              "client_email": "mimir-bucket-access@elated-ranger-349805.iam.gserviceaccount.com",
              "client_id": "107843024972929082971",
              "auth_uri": "https://accounts.google.com/o/oauth2/auth",
              "token_uri": "https://oauth2.googleapis.com/token",
              "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
              "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/mimir-bucket-access%40elated-ranger-349805.iam.gserviceaccount.com",
              "universe_domain": "googleapis.com"
              }

      blocks_storage:
        gcs:
          bucket_name: mimir-blocks

      alertmanager_storage:
        gcs:
          bucket_name: mimir-alertmanager

      ruler_storage:
        gcs:
          bucket_name: mimir-ruler
  metaMonitoring:
    serviceMonitor: enabled
  # small.yaml
  alertmanager:
    persistentVolume:
      enabled: true
    replicas: 1
    resources:
      limits:
        memory: 1.4Gi
      requests:
        cpu: 1
        memory: 1Gi
    statefulSet:
      enabled: true

  compactor:
    persistentVolume:
      size: 20Gi

  distributor:
    replicas: 1

  ingester:
    persistentVolume:
      size: 20Gi
    replicas: 1
    topologySpreadConstraints: {}

  admin-cache:
    enabled: true
    replicas: 1

  chunks-cache:
    enabled: true
    replicas: 1

  index-cache:
    enabled: true
    replicas: 1

  metadata-cache:
    enabled: true

  results-cache:
    enabled: true
    replicas: 1

  minio:
    enabled: false

  overrides_exporter:
    replicas: 1

  querier:
    replicas: 1


  query_frontend:
    replicas: 1
 

  ruler:
    replicas: 1
 

  store_gateway:
    persistentVolume:
      size: 10Gi
    replicas: 3

  nginx:
    replicas: 1

grafana:
  namespaceOverride: "grafana"
